### ISSUE TITLE
Bug: "Execution Reverted for an unknown reason" error

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#327] opened 2023-08-16 14:52 UTC
### What happened 🆘
**A clear and concise description of what the bug is.**
Depositor gets this error message "Execution Reverted for an unknown reason" when trying to stake the yVault tokens.
User has tried at different times over the course of a couple of days and the problem persists. Basic troubleshooting such as hard refresh, clearing cache and opening up browser again, are not working.
![image](https://github.com/yearn/yearn.fi/assets/86468557/de43f473-3d35-4c1b-98d3-397f96f97859)

### To Reproduce 🔂
Deposting via Rabby/Metamask wallet on brave browser to Velodrome ERN - LUSD. 

### More 🔎
Link to conversation thread: https://discord.com/channels/734804446353031319/734811808401063966/1141361692241039380
Another 2 users reported same issue: https://discord.com/channels/734804446353031319/734811808401063966/1140360490875363378
https://discord.com/channels/734804446353031319/734811808401063966/1141410653446361239

**Comment by karelianpie** [comment] 2023-09-10 11:33
Unable to reproduce, closing.

**Closed by karelianpie** 2023-09-10 11:33 UTC
Labels: bug
