### ISSUE TITLE
Bug: bug/feature request submission not working on yearn.fi

### ISSUE THREAD

**Issue by defiglenn** [yearn/yearn.fi#338] opened 2023-09-06 05:18 UTC
### What happened 🆘
**A clear and concise description of what the bug is.**
Button is greyed out when I tested to use it

### To Reproduce 🔂
Go to yearn.fi, bottom right corner click on speech bubble, attempt to submit a bug/feature report

### More 🔎
- Browser : chrome

**Comment by defiglenn** [comment] 2023-09-06 14:34
There's a character limit of 10 characters until the button becomes enabled.

**Comment by karelianpie** [comment] 2023-09-07 18:01
Closing as it's a feature not a bug, as @defiglenn said there's an intentional 10 character limit for the description.

**Closed by karelianpie** 2023-09-07 18:01 UTC
Labels: bug
